MONAI version: 0.9.0rc1+19.g61a0dc35
Numpy version: 1.22.4
Pytorch version: 1.11.0+cu102
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 61a0dc35b8a5edf78487b30c02c7aa0e51fc3409
MONAI __file__: /home/srd/MONAI/monai/__init__.py
Optional dependencies:
Pytorch Ignite version: 0.4.8
Nibabel version: 3.2.2
scikit-image version: 0.19.2
Pillow version: 9.1.1
Tensorboard version: 2.9.0
gdown version: 4.4.0
TorchVision version: 0.12.0+cu102
tqdm version: 4.64.0
lmdb version: 1.3.0
psutil version: 5.9.1
pandas version: 1.4.2
einops version: 0.4.1
transformers version: 4.19.2
mlflow version: 1.26.1
pynrrd version: 0.4.3
For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies
./results
Loading dataset:   3%|▉                          | 3/91 [00:01<00:25,  3.44it/s]
Dataloader Batch Dimensions =  torch.Size([8, 1, 96, 96, 48])
Original Scan Shape = torch.Size([96, 96, 48]),
Segmented Scan Shape = torch.Size([96, 96, 48])
Unique Segmentation Mask Values =  [0. 1.]









Loading dataset: 100%|██████████████████████████| 91/91 [00:21<00:00,  4.26it/s]

Loading dataset: 100%|████████████████████████████| 9/9 [00:02<00:00,  3.87it/s]
----------
epoch 1/100
1/22, train_loss: 0.6835
2/22, train_loss: 0.6851
3/22, train_loss: 0.6819
4/22, train_loss: 0.6802
5/22, train_loss: 0.6854
6/22, train_loss: 0.6720
7/22, train_loss: 0.6738
8/22, train_loss: 0.6796
9/22, train_loss: 0.6757
10/22, train_loss: 0.6661
11/22, train_loss: 0.6772
12/22, train_loss: 0.6631
13/22, train_loss: 0.6700
14/22, train_loss: 0.6732
15/22, train_loss: 0.6666
16/22, train_loss: 0.6680
17/22, train_loss: 0.6687
18/22, train_loss: 0.6678
19/22, train_loss: 0.6564
20/22, train_loss: 0.6523
21/22, train_loss: 0.6572
22/22, train_loss: 0.6588
23/22, train_loss: 0.6636
epoch 1 average loss: 0.6707
saved new best metric model
current epoch: 1 current mean dice: 0.0160
best mean dice: 0.0160 at epoch: 1
----------
epoch 2/100
1/22, train_loss: 0.6461
2/22, train_loss: 0.6626
3/22, train_loss: 0.6552
4/22, train_loss: 0.6561
5/22, train_loss: 0.6567
6/22, train_loss: 0.6588
7/22, train_loss: 0.6476
8/22, train_loss: 0.6387
9/22, train_loss: 0.6536
10/22, train_loss: 0.6578
11/22, train_loss: 0.6547
12/22, train_loss: 0.6462
13/22, train_loss: 0.6441
14/22, train_loss: 0.6322
15/22, train_loss: 0.6511
16/22, train_loss: 0.6378
17/22, train_loss: 0.6483
18/22, train_loss: 0.6423
19/22, train_loss: 0.6497
20/22, train_loss: 0.6381
21/22, train_loss: 0.6469
22/22, train_loss: 0.6458
23/22, train_loss: 0.6483
epoch 2 average loss: 0.6486
----------
epoch 1/100
  0%|                                                   | 0/100 [00:00<?, ?it/s]
  0%|                                                    | 0/23 [00:00<?, ?it/s]

  4%|█▉                                          | 1/23 [00:06<02:28,  6.74s/it]

  9%|███▊                                        | 2/23 [00:10<01:41,  4.85s/it]

 13%|█████▋                                      | 3/23 [00:13<01:25,  4.27s/it]

 17%|███████▋                                    | 4/23 [00:17<01:15,  3.99s/it]

 22%|█████████▌                                  | 5/23 [00:20<01:08,  3.82s/it]

 26%|███████████▍                                | 6/23 [00:24<01:02,  3.70s/it]

 30%|█████████████▍                              | 7/23 [00:28<01:00,  3.76s/it]

 35%|███████████████▎                            | 8/23 [00:31<00:55,  3.68s/it]

Traceback (most recent call last):               | 9/23 [00:35<00:51,  3.65s/it]
  File "/home/srd/anaconda3/envs/instance22/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/srd/anaconda3/envs/instance22/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/srd/anaconda3/envs/instance22/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 152, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "/home/srd/anaconda3/envs/instance22/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 138, in communicate_network_status
    resp = self._communicate_network_status(status)
  File "/home/srd/anaconda3/envs/instance22/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 405, in _communicate_network_status
    resp = self._communicate(req, local=True)
  File "/home/srd/anaconda3/envs/instance22/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/srd/anaconda3/envs/instance22/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/home/srd/anaconda3/envs/instance22/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/srd/anaconda3/envs/instance22/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/srd/anaconda3/envs/instance22/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 170, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/home/srd/anaconda3/envs/instance22/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 127, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "/home/srd/anaconda3/envs/instance22/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 395, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "/home/srd/anaconda3/envs/instance22/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/srd/anaconda3/envs/instance22/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Error in callback <function _WandbInit._pause_backend at 0x7f8d98802b80> (for post_run_cell):
 39%|█████████████████▏                          | 9/23 [00:50<01:19,  5.65s/it]
  0%|                                                   | 0/100 [00:50<?, ?it/s]
Error in callback <function _WandbInit._resume_backend at 0x7f8dc0244f70> (for pre_run_cell):
----------
epoch 1/100
  0%|                                                   | 0/100 [00:00<?, ?it/s]



 13%|█████▋                                      | 3/23 [00:14<01:29,  4.46s/it]

  0%|                                                   | 0/100 [00:16<?, ?it/s]